#YAML Script for DBT:

trigger:
- none

schedules:
- cron: '*/5 * * * *'
  displayName: 'Run Every 5 Minutes'
  branches:
    include:
    - 'main'
  always: true
  batch: false

jobs:
- job: RunDbtModels
  pool:
    vmImage: 'windows-latest'
  
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

 - powershell: |
      # Create a directory for dbt
      New-Item -ItemType Directory -Force -Path C:\dbt

      # Install pip
      Invoke-WebRequest -Uri https://bootstrap.pypa.io/get-pip.py -OutFile C:\dbt\get-pip.py
      python C:\dbt\get-pip.py

      # Upgrade pip and setuptools
      python -m pip install --upgrade pip
      pip install --upgrade setuptools
    displayName: 'Install pip and upgrade setuptools'

  - powershell: |
      # Install dbt and dependencies
      pip install dbt
      pip install dbt-snowflake
    displayName: 'Install dbt and dependencies'

  - powershell: |
      # Install additional dependencies for snowflake-connector-python
      pip install pyopenssl ndg-httpsclient pyasn1
      # Install snowflake-connector-python with pre-built wheel
      pip install snowflake-connector-python --only-binary :all:
    displayName: 'Install snowflake-connector-python and dependencies'

  - script: |
      dbt deps --profiles-dir $(Build.Repository.LocalPath)/dfz --project-dir $(Build.Repository.LocalPath)/dfz
    displayName: 'Install dbt dependencies'

  - script: |
      dbt run --profiles-dir $(Build.Repository.LocalPath)/dfz --project-dir $(Build.Repository.LocalPath)/dfz
    displayName: 'Run dbt models'

  - script: |
      dbt test --profiles-dir $(Build.Repository.LocalPath)/dfz --project-dir $(Build.Repository.LocalPath)/dfz
    displayName: 'Run dbt tests'
