trigger:
- main

schedules:
- cron: "*/5 * * * *"
  displayName: "Every 5 minutes"
  branches:
    include:
    - main

jobs:
- job: RunDbtModels
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
    persistCredentials: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install dbt
      pip install dbt-snowflake
    displayName: 'Install dbt and dependencies'

  - script: 'dbt deps --profiles-dir $(System.DefaultWorkingDirectory)\dfz --project-dir $(System.DefaultWorkingDirectory)\dfz'
    displayName: 'Install dbt dependencies'

  - script: |
      dbt run --profiles-dir $(System.DefaultWorkingDirectory)\dfz --project-dir $(System.DefaultWorkingDirectory)\dfz
    displayName: 'Run dbt models'

  - script: |
      dbt test --profiles-dir $(System.DefaultWorkingDirectory)\dfz --project-dir $(System.DefaultWorkingDirectory)\dfz
    displayName: 'Run dbt tests'
