#YAML Script for DBT:

schedules:
- cron: '*/5 * * * *'
  displayName: "Every 5 minutes"
  branches:
    include:
    - main

jobs:
- job: RunDbtModels
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - checkout: self


  - script: |
      dbt deps --profiles-dir $(Build.Repository.LocalPath)/dfz --project-dir $(Build.Repository.LocalPath)/dfz
    displayName: 'Install dbt dependencies'

  - script: |
      dbt run --profiles-dir $(Build.Repository.LocalPath)/dfz --project-dir $(Build.Repository.LocalPath)/dfz
    displayName: 'Run dbt models'

  - script: |
      dbt test --profiles-dir $(Build.Repository.LocalPath)/dfz --project-dir $(Build.Repository.LocalPath)/dfz
    displayName: 'Run dbt tests'
