name: Run dbt Models

on:
  schedule:
    - cron: '*/5 * * * *'
  
jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - checkout: self

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true

      - script: |
          python -m pip install --upgrade pip
          pip install dbt
          pip install dbt-snowflake
      - script: dbt deps --profiles-dir $(Build.Repository.LocalPath)\dfz --project-dir $(Build.Repository.LocalPath)\dfz

      - script: dbt run --profiles-dir $(Build.Repository.LocalPath)\dfz --project-dir $(Build.Repository.LocalPath)\dfz

      - script: dbt test --profiles-dir $(Build.Repository.LocalPath)\dfz --project-dir $(Build.Repository.LocalPath)\dfz
